### ISSUE TITLE
About the RMSE unit

### ISSUE THREAD

**Issue by guoyage** [m-hasan-n/pooling#1]
First, Thanks yours wonderful research, i have some question about your code, in the test stage, you define the RMSE as pred_rmse = torch.pow(lossVals / counts, 0.5) * 0.3048, but in my opinion, this equation is transformer the unit of feet to the unit of meter, However, in your research, you have change the unit of lossVals to polar coordinate, so I wonder if it is reasonable to directly use the above equation？Thanks

**Comment by m-hasan-n** [comment]
Thanks for your comment and interest in our work. Yes, the formula you refer to, is used to convert from feet to meter. In case of polar coordinates, there are two variables _radius_ (in feet) and _angle_ (in radians). Since a _radian_ represents the ratio of arc length to radius length, it can be considered as a "dimensionless" quantity. Thus, the same formula holds for the polar coordinates case.

**Comment by guoyage** [comment]
> Thanks for your comment and interest in our work. Yes, the formula you refer to, is used to convert from feet to meter. In case of polar coordinates, there are two variables _radius_ (in feet) and _angle_ (in radians). Since a _radian_ represents the ratio of arc length to radius length, it can be considered as a "dimensionless" quantity. Thus, the same formula holds for the polar coordinates case.

Thank you for your reply.
